asterisk.{prerm,postinst}: No automatic restart if the PBX is in use.
And no samples will be written into /etc/asterisk. Take samples from
/usr/share if you want them.

diff --git a/asterisk.postinst b/asterisk.postinst
--- a/asterisk.postinst
+++ b/asterisk.postinst
@@ -101,6 +101,14 @@ case "$1" in
     ;;
 esac
 
+# Since we use a dh_installinit --noscripts in rules,
+# The following is added here manually.
+# This will fail when an asterisk is already running and that is intended.
+if [ -x "/etc/init.d/asterisk" ]; then
+    update-rc.d asterisk defaults >/dev/null
+    invoke-rc.d asterisk start || exit $?
+fi
+
 # dh_installdeb will replace this with shell code automatically
 # generated by other debhelper scripts.
 
