Version update to 16.11.1-0osso0+u20.04

diff --git a/debian/asterisk.postinst b/debian/asterisk.postinst
--- a/debian/asterisk.postinst
+++ b/debian/asterisk.postinst
@@ -101,6 +101,21 @@ case "$1" in
     ;;
 esac
 
+# dh_installinit will add code akin to if $1 = configure and $2 (i.e.
+# update); then invoke-rc.d asterisk restart. We don't want a "hard"
+# restart, but want a restart-convenient instead. So, we must exit here.
+# (By doing this, we don't need the `--noscripts` option to
+# dh_installinit in rules.)
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+       if [ -x "/etc/init.d/asterisk" ] && [ -n "$2" ]; then
+               # Note that we _do_ skip systemd setup here in the
+               # upgrade case. Hope/assume it was configured when
+               # the previous version was installed.
+               invoke-rc.d asterisk restart-convenient || exit 1
+               exit 0
+       fi
+fi
+
 # dh_installdeb will replace this with shell code automatically
 # generated by other debhelper scripts.
 
