debian patches from latest 18.11

diff --git a/debian/rules b/debian/rules
--- a/debian/rules
+++ b/debian/rules
@@ -1,107 +1,115 @@
 #!/usr/bin/make -f
-# Uncomment this to turn on verbose mode.
-#export DH_VERBOSE=1
 
-# Starting with dpkg-dev >= 1.16.1.1 you can use the new buildflags.mk file
-# to set all *FLAGS
-# When building programs that handle untrusted data
-# (parsers, network listeners, etc.),
-#  or run with elevated privileges (PAM, X, etc.),
-#  please enable "PIE" and "BINDNOW" in the build.
-#  The "all" option enables "PIE" and "BINDNOW" and future hardening flags
+# resolve DEB_VERSION_UPSTREAM_REVISION DEB_DISTRIBUTION
+include /usr/share/dpkg/pkg-info.mk
 
-%:
-	dh $@
+# resolve DEB_BUILD_ARCH_OS DEB_HOST_MULTIARCH
+include /usr/share/dpkg/architecture.mk
 
+# enable hardening compiler options
+# see <https://wiki.debian.org/Hardening#Using_Hardening_Options>
+# revive upstream optimization flags unless DEB_BUILD_OPTIONS=noopt
+# code allegedly fails partial-inlining optimization with GCC >= 8.2.1,
+# see <Makefile.rules> and upstream git commit 449dff9
 export DEB_BUILD_MAINT_OPTIONS = hardening=+all
-DPKG_EXPORT_BUILDFLAGS = 1
+ifeq (,$(filter noopt,$(DEB_BUILD_OPTIONS)))
+DEB_CFLAGS_MAINT_STRIP = -O2
+DEB_CFLAGS_MAINT_APPEND = -O3 -fno-partial-inlining
+endif
 include /usr/share/dpkg/buildflags.mk
+
+# Pass CPPFLAGS in the CFLAGS as otherwise the build system will
+# ignore them.
+CFLAGS += $(CPPFLAGS)
+
+LDFLAGS += -Wl,--as-needed
 
 # Sanity check for a stable release:
 SAVED_ABI_HASH = 1fb7f5c06d7a2052e38d021b3d8ca151
 
-export DEB_HOST_GNU_TYPE  ?= $(shell dpkg-architecture -qDEB_HOST_GNU_TYPE)
-export DEB_BUILD_GNU_TYPE ?= $(shell dpkg-architecture -qDEB_BUILD_GNU_TYPE)
+# resolve PJPROJECT version
+PJMAJ = $(shell grep -Po '^export PJ_VERSION_MAJOR\s+:=\s+\K\d+' Xpjproject/version.mak)
+PJMIN = $(shell grep -Po '^export PJ_VERSION_MINOR\s+:=\s+\K\d+' Xpjproject/version.mak)
+PJREV = $(shell grep -Po '^export PJ_VERSION_REV\s+:=\s+\K\d+' Xpjproject/version.mak)
+PJVER := $(PJMAJ)$(if $(PJMIN),.$(PJMIN)$(if $(PJREV),.$(PJREV)))
 
-ifeq ($(DEB_BUILD_GNU_TYPE), $(DEB_HOST_GNU_TYPE))
-  confflags += --build $(DEB_HOST_GNU_TYPE)
-else
-  confflags += --build $(DEB_BUILD_GNU_TYPE) --host $(DEB_HOST_GNU_TYPE)
-endif
-
-# We copy around a number of things in case we're linux:
-BUILD_OS=$(shell dpkg-architecture -qDEB_BUILD_ARCH_OS)
-
-export PROC := $(shell dpkg-architecture -qDEB_BUILD_GNU_CPU)
+PJDIR = debian/build-pjproject
 
 # don't let asterisk mess with build flags
 BUILDFLAGS += AST_FORTIFY_SOURCE= DEBUG= OPTIMIZE=
 
-# show full gcc arguments instead of [CC] and [LD]
+# show full gcc arguments unless DEB_BUILD_OPTIONS=terse
+ifeq (,$(filter terse,$(DEB_BUILD_OPTIONS)))
 BUILDFLAGS += NOISY_BUILD=yes
+endif
 
 BUILDFLAGS += ASTDATADIR=/usr/share/asterisk ASTVARRUNDIR=/var/run/asterisk
 
-ifneq (,$(findstring debug,$(DEB_BUILD_OPTIONS)))
-	ENABLE_DEBUG += --enable-dev-mode
-endif
 ifeq (,$(findstring nostrip,$(DEB_BUILD_OPTIONS)))
 	INSTALL_PROGRAM += -s
 endif
 
-include /usr/share/dpkg/pkg-info.mk
-DEBVERSION:=$(DEB_VERSION)
-DEB_NOEPOCH_VERSION:=$(shell echo $(DEBVERSION) | cut -d':' -f 2)
+ADDONS_ENABLE = app_macro app_voicemail_imap app_voicemail_odbc
+ADDONS_ENABLE += app_mysql res_config_mysql cdr_mysql
+ADDONS_ENABLE += chan_mobile chan_ooh323
+ADDONS_ENABLE += aelparse format_mp3 smsq TEST_FRAMEWORK
+ADDONS_DISABLE = BUILD_NATIVE
+ifneq (,$(findstring debug,$(DEB_BUILD_OPTIONS)))
+ADDONS_ENABLE += BETTER_BACKTRACES DEBUG_THREADS
+endif
 
 # make sure we have 'fetch' . We need to have either wget or fetch
 # on the system. However it is generally not a good idea to actually
-# get remote tarballs at build time. So if neither wget nor fetch 
+# get remote tarballs at build time. So if neither wget nor fetch
 # happen to be installed, the configure script will find a dummy
 # fetch script that always returns an error.
 FETCH_ENV = PATH=$$PATH:$(CURDIR)/debian/dummyprogs
 
 # resolve if release is experimental
-EXP_RELEASE := $(if $(shell dpkg-parsechangelog | grep '^Distribution: \(experimental\|UNRELEASED\)'),exp)
+EXP_RELEASE = $(filter experimental% UNRELEASED,$(DEB_DISTRIBUTION))
 
 override_dh_autoreconf:
 	if [ ! -r configure.debian_sav ]; then cp -a configure configure.debian_sav; fi
 	[ -f .version.debian_sav ] || cp -a .version .version.debian_sav
-	echo $(DEB_NOEPOCH_VERSION) > .version
+	echo $(DEB_VERSION_UPSTREAM_REVISION) > .version
 	dh_autoreconf -- ./bootstrap.sh
 
-# Make sure the configure script gets an CFLAGS parameter. Otherwise
-# it will build with -march=native
-# Pass CPPFLAGS in the CFLAGS as otherwise the build system will
-# ignore them.
+execute_before_dh_auto_configure:
+	chmod 755 debian/dummyprogs/fetch
+	# don't create DSFG-free version of pjproject source (keep upstream)
+
+	cp --force --recursive --target-directory=. Xamr/codecs Xamr/include Xamr/res
+
+	rm --force addons/mp3
+	mkdir addons/mp3
+	cp --force --target-directory=addons/mp3 Xmp3/*
+
+	cp --force --recursive --target-directory=. Xopus/codecs Xopus/formats
+
 override_dh_auto_configure:
-	chmod 755 $(CURDIR)/debian/dummyprogs/fetch
-	# Skip debian DSFG-free version of pjproject fix
-	$(FETCH_ENV) ./configure			\
-		CFLAGS="-fgnu89-inline $(CFLAGS) $(CPPFLAGS)" LDFLAGS="$(LDFLAGS) -Wl,--as-needed" \
-		--host=$(DEB_HOST_GNU_TYPE)		\
-		--build=$(DEB_BUILD_GNU_TYPE)		\
-		--prefix=/usr				\
-		--mandir=\$${prefix}/share/man		\
-		--infodir=\$${prefix}/share/info	\
-		--disable-asteriskssl			\
-		--with-gsm				\
-		--with-imap=system			\
-		--without-pwlib				\
+	TMPDIR="$(CURDIR)/$(PJDIR)" $(FETCH_ENV) dh_auto_configure -- \
+		--disable-asteriskssl \
+		--with-gsm \
+		--with-imap=system \
+		--without-pwlib \
 		$(if $(EXP_RELEASE),,--without-sdl) \
-		${ENABLE_DEBUG} || { cat config.log; exit 1; }
+		$(if $(findstring debug,$(DEB_BUILD_OPTIONS)),--enable-dev-mode) \
+		|| { cat config.log; exit 1; }
 
 #		--with-cap \
 
+execute_before_dh_auto_build:
+	$(MAKE) menuselect.makeopts BUILD_CFLAGS="$(CFLAGS)" BUILD_LDFLAGS="$(LDFLAGS)"
+	for module in $(ADDONS_ENABLE); do menuselect/menuselect --enable $$module menuselect.makeopts; done
+	for module in $(ADDONS_DISABLE); do menuselect/menuselect --disable $$module menuselect.makeopts; done
+
 override_dh_auto_build:
-	$(MAKE) menuselect.makeopts BUILD_CFLAGS="$(CFLAGS) $(CPPFLAGS)" BUILD_LDFLAGS="$(LDFLAGS)"
-	menuselect/menuselect --enable app_macro menuselect.makeopts
-	@if [ "x${ENABLE_DEBUG}" != "x" ] ; then \
-		menuselect/menuselect --enable BETTER_BACKTRACES menuselect.makeopts ; \
-		menuselect/menuselect --enable DEBUG_THREADS menuselect.makeopts ; \
-	fi
 	$(FETCH_ENV) dh_auto_build -- $(BUILDFLAGS)
+
+execute_after_dh_auto_build:
 	# Sanity check: don't break the ABI for modules:
-	@abi_hash=`awk -F'"' '/AST_BUILDOPT_SUM/ {print $$2}' include/asterisk/buildopts.h`; \
+	@abi_hash=$$(awk -F'"' '/AST_BUILDOPT_SUM/ {print $$2}' \
+	  include/asterisk/buildopts.h); \
 	  if [ "$$abi_hash" != "$(SAVED_ABI_HASH)" ]; then \
 	    echo "Debian packaging problem: ABI checksum changed."; \
 	    echo "  Was: $(SAVED_ABI_HASH)"; \
@@ -110,73 +118,68 @@ override_dh_auto_build:
 	    [ -n "$(EXP_RELEASE)" ] || exit 1; \
 	  fi
 
+	pod2man --center="Asterisk packaging helper tools" \
+		--release="asterisk $(DEB_VERSION_UPSTREAM_REVISION)" \
+		debian/debhelper/dh_asterisk \
+		debian/dh_asterisk.1
+
 SND_FILE=asterisk-core-sounds-en-gsm-1.4.20.tar.gz
-override_dh_clean:
-	if [ -r sounds/$(SND_FILE) ]; then mv sounds/$($SND_FILE) debian/; fi
+execute_before_dh_clean:
+	[ ! -r sounds/$(SND_FILE) ] || mv sounds/$($SND_FILE) debian/
 	GREP=grep AWK=awk $(MAKE) distclean
-	if [ -r debian/$(SND_FILE) ]; then mv debian/$(SND_FILE) sounds/; fi
+	[ ! -r debian/$(SND_FILE) ] || mv debian/$(SND_FILE) sounds/
 
 	[ ! -f .version.debian_sav ] || mv .version.debian_sav .version
-	if [ -f configure.debian_sav ]; then mv configure.debian_sav configure; fi
-
-	dh_clean
+	[ ! -f configure.debian_sav ] || mv configure.debian_sav configure
 
 override_dh_gencontrol:
-	AST_BUILDOPT_SUM=`grep AST_BUILDOPT_SUM include/asterisk/buildopts.h  | sed -e 's/.\+ "\(.\+\)\"/\1/g'`; \
+	AST_BUILDOPT_SUM=$$(grep AST_BUILDOPT_SUM include/asterisk/buildopts.h  \
+		| sed -e 's/.\+ "\(.\+\)\"/\1/g'); \
 		dh_gencontrol -- -Vasterisk:ABI=$$AST_BUILDOPT_SUM
 
 REMOVED_PROTO_CONFS = dundi mgcp skinny unistim
-REMOVED_PROTO_FILES = $(REMOVED_PROTO_CONFS:%=$(CURDIR)/debian/tmp/etc/asterisk/%.conf)
-SUBPACKS_EXTRA = \
-		 voicemail voicemail-odbcstorage voicemail-imapstorage \
-		 ooh323 mysql mp3
-ifeq (linux,$(BUILD_OS))
-SUBPACKS_EXTRA += dahdi mobile tests vpb
+REMOVED_PROTO_FILES = $(REMOVED_PROTO_CONFS:%=debian/tmp/etc/asterisk/%.conf)
+SUBPACKS_EXTRA = ooh323 mysql mp3
+ifeq (linux,$(DEB_BUILD_ARCH_OS))
+SUBPACKS_EXTRA += dahdi mobile tests
 endif
-SUBPACKS_EXTRA_DIRS = $(SUBPACKS_EXTRA:%=$(CURDIR)/debian/asterisk-%)
-SUBPACKS_EXTRA_DIRS_MOD = $(SUBPACKS_EXTRA_DIRS:%=%/usr/lib/asterisk/modules)
+SUBPACKS_EXTRA_DIRS = $(SUBPACKS_EXTRA:%=debian/asterisk-%)
+SUBPACKS_EXTRA_DIRS_MOD = $(SUBPACKS_EXTRA_DIRS:%=%/usr/lib/$(DEB_HOST_MULTIARCH)/asterisk/modules)
 
 override_dh_auto_install:
-	$(FETCH_ENV) dh_auto_install -- $(BUILDFLAGS) -j1 config samples
-	install -m644 -D debian/examples/safe_asterisk/startup.d--mail-backtrace.sh \
-		$(CURDIR)/debian/tmp/etc/asterisk/startup.d/mail-backtrace.sh
-	cp -a configs $(CURDIR)/debian/tmp/usr/share/asterisk/conf
+	$(FETCH_ENV) dh_auto_install -- $(BUILDFLAGS) -j1 config samples install-headers
+
+execute_after_dh_auto_install:
+	cp -a configs debian/tmp/usr/share/asterisk/conf
 	$(RM) -f $(REMOVED_PROTO_FILES)
-	mkdir -p $(CURDIR)/debian/tmp/usr/bin/
-	mkdir -p $(CURDIR)/debian/tmp/usr/share/man/man1
-	mkdir -p $(CURDIR)/debian/tmp/usr/share/dahdi/span_config.d
-	cp -a debian/asterisk-config-custom $(CURDIR)/debian/tmp/usr/bin/
-	cp -a debian/asterisk-config-custom.1 $(CURDIR)/debian/tmp/usr/share/man/man1/
-	cp -a debian/50-asterisk $(CURDIR)/debian/tmp/usr/share/dahdi/span_config.d/
-	$(RM) -f $(CURDIR)/debian/tmp/usr/sbin/conf2ael
-	$(RM) -f $(CURDIR)/debian/tmp/usr/sbin/muted
-	$(RM) -f $(CURDIR)/debian/tmp/usr/sbin/streamplayer
-	$(RM) -f $(CURDIR)/debian/tmp/usr/sbin/stereorize
-	$(RM) -f $(CURDIR)/debian/tmp/usr/sbin/hashtest*
-	$(RM) -f $(CURDIR)/debian/tmp/usr/sbin/refcounter
+	mkdir -p debian/tmp/usr/bin/
+	mkdir -p debian/tmp/usr/share/man/man1
+	mkdir -p debian/tmp/usr/share/dahdi/span_config.d
+	cp -a debian/asterisk-config-custom debian/tmp/usr/bin/
+	cp -a debian/asterisk-config-custom.1 debian/tmp/usr/share/man/man1/
+	cp -a debian/50-asterisk debian/tmp/usr/share/dahdi/span_config.d/
+	$(RM) -f debian/tmp/usr/sbin/conf2ael
+	$(RM) -f debian/tmp/usr/sbin/muted
+	$(RM) -f debian/tmp/usr/sbin/streamplayer
+	$(RM) -f debian/tmp/usr/sbin/stereorize
+	$(RM) -f debian/tmp/usr/sbin/hashtest*
+	$(RM) -f debian/tmp/usr/sbin/refcounter
 
-override_dh_install-arch:
-	dh_install
-	extra_packs=`find $(SUBPACKS_EXTRA_DIRS_MOD) -name '*.so' -printf '%f\n'`\
-		    ; cd $(CURDIR)/debian/asterisk-modules/usr/lib/asterisk/modules \
-		    && rm -f $$extra_packs
+execute_after_dh_install-arch:
+	extra_packs=$$(find $(SUBPACKS_EXTRA_DIRS_MOD) -name '*.so' -printf '%f\n');\
+	  cd debian/asterisk-modules/usr/lib/$(DEB_HOST_MULTIARCH)/asterisk/modules \
+	  && rm -f $$extra_packs
 
-	# Rename dh_install file for -imapstorage and -odbcstorage.
-	mv $(CURDIR)/debian/asterisk-voicemail-imapstorage/usr/lib/asterisk/modules/app_voicemail_imapstorage.so \
-		$(CURDIR)/debian/asterisk-voicemail-imapstorage/usr/lib/asterisk/modules/app_voicemail.so
-	mv $(CURDIR)/debian/asterisk-voicemail-odbcstorage/usr/lib/asterisk/modules/app_voicemail_odbcstorage.so \
-		$(CURDIR)/debian/asterisk-voicemail-odbcstorage/usr/lib/asterisk/modules/app_voicemail.so
+override_dh_installchangelogs:
+	dh_installchangelogs -- CHANGES
 
-override_dh_fixperms:
-	dh_fixperms
+execute_after_dh_fixperms:
 	# should follow dh_fixperms; asterisk configurations may contain
 	# sensitive information, such as passwords
-	if [ -d $(CURDIR)/debian/asterisk-config ]; then \
-		chmod o-rwx $(CURDIR)/debian/asterisk-config/etc/asterisk/*; \
-		chmod o+rx  $(CURDIR)/debian/asterisk-config/etc/asterisk/manager.d; \
+	if [ -d debian/asterisk-config ]; then \
+		chmod o-rwx debian/asterisk-config/etc/asterisk/*; \
+		chmod o+rx  debian/asterisk-config/etc/asterisk/manager.d; \
 	fi
 
-override_dh_strip:
-	dh_strip -a --dbgsym-migration='asterisk-dbg (<< 1:13.12.1~dfsg-1~)'
-
-# .PHONY: binary-indep binary-arch binary install
+%:
+	dh $@
